language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-infragistics-sample' ]; then cd .. && eval "mv $currentfolder generator-infragistics-sample" && cd generator-infragistics-sample; fi

